# Generated by Django 6.0.4 on 2026-05-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0005_remove_invoice_invoice_subtotal_non_negative_and_more"),
        ("payments", "0002_payment_alter_stripewebhookevent_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopifyWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(max_length=255)),
                ("shop_domain", models.CharField(blank=True, max_length=255)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-received_at",),
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="shopify_payment_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("ACH", "ACH"),
                    ("WIRE", "Wire"),
                    ("CHECK", "Check"),
                    ("SHOPIFY", "Shopify"),
                    ("STRIPE", "Stripe"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["shopify_payment_id"], name="payments_pa_shopify_2776af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shopifywebhookevent",
            index=models.Index(
                fields=["event_type", "received_at"],
                name="payments_sh_event_t_e06b7a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shopifywebhookevent",
            index=models.Index(
                fields=["shop_domain", "received_at"],
                name="payments_sh_shop_do_a8f37d_idx",
            ),
        ),
    ]
