# Generated by Django 6.0.4 on 2026-05-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fulfillment", "0001_initial"),
        ("orders", "0002_alter_order_options_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shipment",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(fields=["status"], name="fulfillment_status_af4d61_idx"),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["shipped_at"], name="fulfillment_shipped_ebc5d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["order", "status"], name="fulfillment_order_i_31e46e_idx"
            ),
        ),
    ]
