# Generated by Django 6.0.4 on 2026-05-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fulfillment", "0002_alter_shipment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="shopify_fulfillment_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shopify_fulfillment_order_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
