# Generated by Django 6.0.4 on 2026-05-04 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "customers",
            "0003_alter_customer_options_alter_shippingaddress_options_and_more",
        ),
        ("pricing", "0001_initial"),
        ("products", "0004_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerprice",
            options={"ordering": ("customer__name", "product__sku", "-effective_date")},
        ),
        migrations.AlterModelOptions(
            name="customerproduct",
            options={"ordering": ("customer__name", "product__sku")},
        ),
        migrations.AlterField(
            model_name="customerprice",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_contracts",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="customerprice",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_prices",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="customerproduct",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_approvals",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="customerproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_approvals",
                to="products.product",
            ),
        ),
        migrations.AddIndex(
            model_name="customerprice",
            index=models.Index(
                fields=["customer", "product"], name="pricing_cus_custome_052e22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerprice",
            index=models.Index(
                fields=["effective_date", "expiration_date"],
                name="pricing_cus_effecti_bbbe9a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customerproduct",
            index=models.Index(
                fields=["customer", "active"], name="pricing_cus_custome_0c94cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerproduct",
            index=models.Index(
                fields=["product", "active"], name="pricing_cus_product_799d26_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customerprice",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)),
                name="customer_price_unit_price_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="customerprice",
            constraint=models.CheckConstraint(
                condition=models.Q(("minimum_quantity__gt", 0)),
                name="customer_price_minimum_qty_gt_zero",
            ),
        ),
    ]
