# Generated by Django 6.0.4 on 2026-05-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        (
            "customers",
            "0003_alter_customer_options_alter_shippingaddress_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ("username",)},
        ),
        migrations.AddField(
            model_name="user",
            name="is_warehouse_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer_user", "Customer User"),
                    ("warehouse_staff", "Warehouse Staff"),
                    ("admin", "Admin"),
                ],
                db_index=True,
                default="customer_user",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="accounts_us_role_1fa9a5_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active"], name="accounts_us_is_acti_a5841d_idx"
            ),
        ),
    ]
