# Generated by Django 6.0.4 on 2026-05-07 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_backfill_user_roles_and_default_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_sales_lead",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_sales_rep",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "sales_lead"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer_user", "Customer User"),
                    ("warehouse_staff", "Warehouse Staff"),
                    ("sales_rep", "Sales Rep"),
                    ("sales_lead", "Sales Lead"),
                    ("admin", "Admin"),
                ],
                db_index=True,
                default="admin",
                max_length=32,
            ),
        ),
    ]
