# Generated by Django 6.0.4 on 2026-05-07 04:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_invited_by_activitylog_customerinvitation"),
        ("customers", "0005_customer_sales_rep"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetailerLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("store_name", models.CharField(blank=True, max_length=255)),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_retailer_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retailer_leads",
                        to="customers.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RetailerAccountCreationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_retailer_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_tokens",
                        to="accounts.retailerlead",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="retailerlead",
            index=models.Index(fields=["email"], name="accounts_re_email_8ded34_idx"),
        ),
        migrations.AddIndex(
            model_name="retaileraccountcreationtoken",
            index=models.Index(fields=["token"], name="accounts_re_token_1d04fd_idx"),
        ),
        migrations.AddIndex(
            model_name="retaileraccountcreationtoken",
            index=models.Index(
                fields=["expires_at"], name="accounts_re_expires_5e694b_idx"
            ),
        ),
    ]
