# Generated by Django 6.0.4 on 2026-05-12 22:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_retailerlead_retaileraccountcreationtoken_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailerlead",
            name="phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name="RetailerMarketingPageToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_slug",
                    models.CharField(
                        choices=[("free-sample", "Free Sample")],
                        default="free-sample",
                        max_length=64,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Optional campaign/template source label.",
                        max_length=120,
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("first_clicked_at", models.DateTimeField(blank=True, null=True)),
                ("last_clicked_at", models.DateTimeField(blank=True, null=True)),
                ("click_count", models.PositiveIntegerField(default=0)),
                ("last_click_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("last_click_user_agent", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_marketing_page_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketing_page_tokens",
                        to="accounts.retailerlead",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["token"], name="accounts_re_token_5fd110_idx"),
                    models.Index(
                        fields=["page_slug", "created_at"],
                        name="accounts_re_page_sl_b772c4_idx",
                    ),
                    models.Index(
                        fields=["last_clicked_at"],
                        name="accounts_re_last_cl_c33262_idx",
                    ),
                ],
            },
        ),
    ]
