# Generated by Django 6.0.4 on 2026-05-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_retailerlead_phone_retailermarketingpagetoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailermarketingpagetoken",
            name="is_test",
            field=models.BooleanField(default=False),
        ),
    ]
