# Generated by Django 6.0.4 on 2026-05-14 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_retailermarketingpagetoken_is_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreeSampleSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=120)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=50)),
                ("business_name", models.CharField(max_length=255)),
                ("shipping_address", models.TextField()),
                ("business_type", models.CharField(max_length=255)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="free_sample_submission",
                        to="accounts.retailerlead",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="free_sample_submissions",
                        to="accounts.retailermarketingpagetoken",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source"], name="accounts_fr_source_79f139_idx"
                    ),
                    models.Index(
                        fields=["submitted_at"], name="accounts_fr_submitt_0d78ae_idx"
                    ),
                    models.Index(fields=["email"], name="accounts_fr_email_a65cc9_idx"),
                ],
            },
        ),
    ]
