# Generated by Django 6.0.4 on 2026-05-03 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "shipping_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SENT", "Sent"),
                            ("OPEN", "Open"),
                            ("PAID", "Paid"),
                            ("PARTIALLY_PAID", "Partially Paid"),
                            ("OVERDUE", "Overdue"),
                            ("VOID", "Void"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("stripe_invoice_id", models.CharField(blank=True, max_length=255)),
                ("stripe_hosted_invoice_url", models.URLField(blank=True)),
                ("stripe_invoice_pdf", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("subtotal__gte", 0)),
                        name="invoice_subtotal_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("shipping_total__gte", 0)),
                        name="invoice_shipping_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("tax_total__gte", 0)),
                        name="invoice_tax_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("total__gte", 0)),
                        name="invoice_total_non_negative",
                    ),
                ],
            },
        ),
    ]
