# Generated by Django 6.0.4 on 2026-05-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="shipping_carrier",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="invoice",
            name="shipping_currency",
            field=models.CharField(default="usd", max_length=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="shipping_quote_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="shipping_quote_status",
            field=models.CharField(
                choices=[
                    ("NOT_QUOTED", "Not Quoted"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                ],
                default="NOT_QUOTED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="shipping_quoted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="shipping_rate_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="invoice",
            name="shipping_service",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
