# Generated by Django 6.0.4 on 2026-05-04 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_customer_preferred_carrier"),
        (
            "invoicing",
            "0002_invoice_shipping_carrier_invoice_shipping_currency_and_more",
        ),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="invoice",
            name="invoice_subtotal_non_negative",
        ),
        migrations.RemoveConstraint(
            model_name="invoice",
            name="invoice_total_non_negative",
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_kind",
            field=models.CharField(
                choices=[
                    ("PRIMARY", "Primary"),
                    ("ADJUSTMENT_DEBIT", "Adjustment Debit"),
                    ("ADJUSTMENT_CREDIT", "Adjustment Credit"),
                ],
                default="PRIMARY",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="parent_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="adjustments",
                to="invoicing.invoice",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="pdf_file",
            field=models.FileField(blank=True, upload_to="invoices/"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="shipping_input_source",
            field=models.CharField(
                choices=[
                    ("ESTIMATED_API", "Estimated API"),
                    ("MANUAL_OVERRIDE", "Manual Override"),
                    ("FALLBACK_ZERO", "Fallback Zero"),
                ],
                default="FALLBACK_ZERO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="orders.order",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("invoice_kind", "PRIMARY")),
                fields=("order", "invoice_kind"),
                name="unique_primary_invoice_per_order",
            ),
        ),
    ]
