# Generated by Django 6.0.4 on 2026-05-04 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "customers",
            "0003_alter_customer_options_alter_shippingaddress_options_and_more",
        ),
        ("invoicing", "0003_remove_invoice_invoice_subtotal_non_negative_and_more"),
        ("orders", "0002_alter_order_options_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"ordering": ("-created_at",)},
        ),
        migrations.RemoveConstraint(
            model_name="invoice",
            name="unique_primary_invoice_per_order",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice",
                to="orders.order",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["customer", "status"], name="invoicing_i_custome_f28b76_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["due_date"], name="invoicing_i_due_dat_92e42f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["stripe_invoice_id"], name="invoicing_i_stripe__5aa224_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal__gte", 0)),
                name="invoice_subtotal_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("total__gte", 0)), name="invoice_total_non_negative"
            ),
        ),
    ]
