# Generated by Django 6.0.4 on 2026-05-07 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_customer_shopify_customer_id"),
        ("invoicing", "0004_alter_invoice_options_and_more"),
        ("orders", "0003_order_shopify_order_id_order_shopify_order_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="invoice",
            name="invoice_subtotal_non_negative",
        ),
        migrations.RemoveConstraint(
            model_name="invoice",
            name="invoice_total_non_negative",
        ),
        migrations.AddField(
            model_name="invoice",
            name="shopify_draft_order_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="invoice",
            name="shopify_hosted_invoice_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="shopify_order_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="orders.order",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["shopify_draft_order_id"], name="invoicing_i_shopify_bbdc9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["shopify_order_id"], name="invoicing_i_shopify_b3b889_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("invoice_kind", "ADJUSTMENT_CREDIT"),
                    ("subtotal__gte", 0),
                    _connector="OR",
                ),
                name="invoice_subtotal_valid_by_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("invoice_kind", "ADJUSTMENT_CREDIT"),
                    ("total__gte", 0),
                    _connector="OR",
                ),
                name="invoice_total_valid_by_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("invoice_kind", "PRIMARY")),
                fields=("order", "invoice_kind"),
                name="unique_primary_invoice_per_order",
            ),
        ),
    ]
