# Generated by Django 6.0.4 on 2026-05-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="preferred_carrier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Auto (Best Available)"),
                    ("UPS", "UPS"),
                    ("USPS", "USPS"),
                    ("FEDEX", "FedEx"),
                    ("DHL", "DHL"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
