# Generated by Django 6.0.4 on 2026-05-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_customer_preferred_carrier"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="shippingaddress",
            options={"ordering": ("customer__name", "label")},
        ),
        migrations.AddField(
            model_name="customer",
            name="billing_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["is_active"], name="customers_c_is_acti_91d305_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["payment_terms"], name="customers_c_payment_de725a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shippingaddress",
            index=models.Index(
                fields=["customer", "is_active"], name="customers_s_custome_85d435_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shippingaddress",
            index=models.Index(
                fields=["customer", "is_default"], name="customers_s_custome_6acdd6_idx"
            ),
        ),
    ]
