# Generated by Django 6.0.4 on 2026-05-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "customers",
            "0003_alter_customer_options_alter_shippingaddress_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="shopify_customer_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
