# Generated by Django 6.0.4 on 2026-05-07 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_customer_shopify_customer_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="sales_rep",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__in": ["sales_rep", "sales_lead"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_customers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
