# Generated by Django 6.0.4 on 2026-05-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_options_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shopify_order_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="shopify_order_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
