# Generated by Django 6.0.4 on 2026-05-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_shopify_order_id_order_shopify_order_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
