# Generated by Django 6.0.4 on 2026-05-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shipping_dimension_unit",
            field=models.CharField(
                choices=[("in", "Inches"), ("cm", "Centimeters")],
                default="in",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shipping_height",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shipping_length",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shipping_package_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="shipping_weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shipping_weight_unit",
            field=models.CharField(
                choices=[("oz", "Ounces"), ("lb", "Pounds")], default="oz", max_length=8
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shipping_width",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
