# Generated by Django 6.0.4 on 2026-05-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_shipping_dimension_unit_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("sku",)},
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["active"], name="products_pr_active_7d1f9b_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="products_pr_name_9ff0a3_idx"),
        ),
    ]
