# Generated by Django 6.0.4 on 2026-05-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shopify_product_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="shopify_variant_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
